name: 'Setup Ruby Pkgs'
description: 'Cross platform action for setting up Ruby build environments.  Runs ruby/setup-ruby, see input info'
author: 'MSP-Greg'
inputs:
  ruby-version:
    description: 'Used by ruby/setup-ruby.  Ruby version.  A value of "none" will bypass running ruby/setup-ruby'
    required: false
    default: 'default'
  bundler:
    description: 'Used by ruby/setup-ruby.  The version of Bundler to install. Either none, 1, 2, latest or Gemfile.lock. The default tries Gemfile.lock and otherwise uses latest.'
    required: false
    default: 'default'
  bundler-cache:
    description: 'Used by ruby/setup-ruby.  Run "bundle install", and cache the result automatically. Either true or false.'
    required: false
    default: 'false'
  working-directory:
    description: 'Used by ruby/setup-ruby.  The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.'
    required: false
    default: '.'
  apt-get:
    description: 'Ubuntu - install packages'
    default: ''
  brew:
    description: 'macOS - install packages'
    default: ''
  mingw:
    description: 'MinGW - install MSYS2 mingw64 packages'
    default: ''
  msys2:
    description: 'MinGW - install MSYS2 msys2 packages'
    default: ''
  mswin:
    description: 'mswin - install MSYS2 packages (mingw64 packages need prefix)'
    default: ''
  choco:
    description: 'mswin - install Chocolatey packages'
    default: ''
  vcpkg:
    description: 'mswin - install vcpkg packages'
    default: ''
  setup-ruby-ref:
    description: 'Base ruby-setup repository. It is executed before installing packages.'
    default: 'ruby/setup-ruby/v1'
runs:
  using: 'node12'
  main: 'dist/index.js'
